name: Build & Release

on:
  push:
    tags:
      - 'v*'
jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build . -t hpermission
          docker tag hpermission ${{ secrets.DOCKER_USERNAME }}/hpermission:${GITHUB_REF#refs/*/}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/hpermission
